# Caminho para o arquivo principal de log de mudanças
changelog-file: db/changelog/db.changelog-master.xml

#Configurações de Conexão 
#Usando mariadb/mysql
url: jdbc:mariadb://localhost:3306/ministerioatos
username: root
password: 
driver: org.mariadb.jdbc.Driver
classpath: C:/Program Files/liquibase/internal/lib/mariadb-java-client.jar


# Usando supabase (postgres)
# url: jdbc:postgresql://db.iqivahbrqunvviutnvsf.supabase.co:5432/postgres?sslmode=require
# username: postgres
# password: 
# driver: org.postgresql.Driver
# classpath: C:/Program Files/liquibase/internal/lib/postgresql.jar
# liquibase.hub.mode=off
liquibase.hub.mode=off
