# Caminho para o arquivo principal de log de mudanças
changelog-file: db/changelog/db.changelog-master.xml

# Configurações de Conexão (Exemplo para PostgreSQL)
url: jdbc:mariadb://localhost:3306/ministerioatos
username: root
password: 
driver: org.mariadb.jdbc.Driver

# Caminho para o driver JDBC (se não estiver no seu PATH)
classpath: C:/Program Files/liquibase/internal/lib/mariadb-java-client.jar
liquibase.hub.mode=off
